[home/cli/hledger] Use argbash in some scripts

diff --git a/home/yeldir/optional/desktop/office/hledger-scripts/hlb b/home/yeldir/optional/desktop/office/hledger-scripts/hlb
--- a/home/yeldir/optional/desktop/office/hledger-scripts/hlb
+++ b/home/yeldir/optional/desktop/office/hledger-scripts/hlb
@@ -1,35 +1,94 @@
 #!/usr/bin/env bash
 
-TREE_FLAGS='--tree'
+# ARG_OPTIONAL_BOOLEAN([tree],[t],[show account list as a tree],[on])
+# ARG_HELP([Show an overview of the current balance of the main accounts.])
+# ARGBASH_GO()
+# needed because of Argbash --> m4_ignore([
+### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
+# Argbash is a bash code generator used to get arguments parsing right.
+# Argbash is FREE SOFTWARE, see https://argbash.io for more info
 
-help() {
-  echo "Usage: hlb [-t|--no-tree]"
-  echo ""
-  echo "  -t|--no-tree  Show account as a flat list instead of a tree"
-  echo "  -h|--help     Show this help text"
+
+die()
+{
+	local _ret="${2:-1}"
+	test "${_PRINT_HELP:-no}" = yes && print_help >&2
+	echo "$1" >&2
+	exit "${_ret}"
 }
 
-while [[ $# -gt 0 ]]; do
-  case $1 in
-    -t|--no-tree)
-      TREE_FLAGS=''
-      shift;
-      ;;
-    -h|--help)
-      help
-      exit 0
-      ;;
-    *)
-      echo "Unknown option ${1}"
-      help
-      exit 1
-      ;;
-  esac
-done
+
+begins_with_short_option()
+{
+	local first_option all_short_options='th'
+	first_option="${1:0:1}"
+	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+}
+
+# THE DEFAULTS INITIALIZATION - OPTIONALS
+_arg_tree="on"
+
+
+print_help()
+{
+	printf '%s\n' "Show an overview of the current balance of the main accounts."
+	printf 'Usage: %s [-t|--(no-)tree] [-h|--help]\n' "$0"
+	printf '\t%s\n' "-t, --tree, --no-tree: show account list as a tree (on by default)"
+	printf '\t%s\n' "-h, --help: Prints help"
+}
+
+
+parse_commandline()
+{
+	while test $# -gt 0
+	do
+		_key="$1"
+		case "$_key" in
+			-t|--no-tree|--tree)
+				_arg_tree="on"
+				test "${1:0:5}" = "--no-" && _arg_tree="off"
+				;;
+			-t*)
+				_arg_tree="on"
+				_next="${_key##-t}"
+				if test -n "$_next" -a "$_next" != "$_key"
+				then
+					{ begins_with_short_option "$_next" && shift && set -- "-t" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+				fi
+				;;
+			-h|--help)
+				print_help
+				exit 0
+				;;
+			-h*)
+				print_help
+				exit 0
+				;;
+			*)
+				_PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
+				;;
+		esac
+		shift
+	done
+}
+
+parse_commandline "$@"
+
+# OTHER STUFF GENERATED BY Argbash
+
+### END OF CODE GENERATED BY Argbash (sortof) ### ])
+# [ <-- needed because of Argbash
+
+TREE_FLAG=""
+if [[ $_arg_tree = "on" ]]; then
+	TREE_FLAG="--tree"
+fi
 
 hledger balancesheetequity \
-    --historical \
-    --market \
-    "${TREE_FLAGS}" \
-    date:today \
-    "${HL_MAIN_ACCOUNTS[@]}"
+	--historical \
+	--market \
+	"${TREE_FLAG}" \
+	date:today \
+	"${HL_MAIN_ACCOUNTS[@]}"
+
+# ] <-- needed because of Argbash
diff --git a/home/yeldir/optional/desktop/office/hledger-scripts/hlbudget b/home/yeldir/optional/desktop/office/hledger-scripts/hlbudget
--- a/home/yeldir/optional/desktop/office/hledger-scripts/hlbudget
+++ b/home/yeldir/optional/desktop/office/hledger-scripts/hlbudget
@@ -1,63 +1,134 @@
 #!/usr/bin/env bash
 
-help() {
-  echo "Usage: hlbudget [-v|--verbose] [-m|--months]"
-  echo ""
-  echo "  -v|--verbose  Include empty accounts in output"
-  echo "  -m|--months   Override how many months into the the past the budget should show"
-  echo "  -p|--period   Override the period by which the budget is grouped. Try 'monthly', 'quarterly' or 'yearly'."
-  echo "     --help     Show this help"
+# ARG_OPTIONAL_BOOLEAN([verbose],[v],[Include empty accounts in output.])
+# ARG_OPTIONAL_SINGLE([months],[m],[How many months should be shown.],[5])
+# ARG_OPTIONAL_SINGLE([period],[p],[The period by which the budget is grouped. Try 'monthly', 'quarterly' or 'yearly'.],[monthly])
+# ARG_HELP([])
+# ARGBASH_GO()
+# needed because of Argbash --> m4_ignore([
+### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
+# Argbash is a bash code generator used to get arguments parsing right.
+# Argbash is FREE SOFTWARE, see https://argbash.io for more info
+
+
+die()
+{
+	local _ret="${2:-1}"
+	test "${_PRINT_HELP:-no}" = yes && print_help >&2
+	echo "$1" >&2
+	exit "${_ret}"
 }
 
-VERBOSE_FLAGS=''
-MONTHS=5
-PERIOD='monthly'
 
-while [[ $# -gt 0 ]]; do
-  case $1 in
-    -v|--verbose)
-      VERBOSE_FLAGS='--empty'
-      shift;
-      ;;
-    -m|--months)
-      MONTHS="${2}"
-      shift; shift;
-      ;;
-    -p|--period)
-      PERIOD="${2}"
-      shift; shift;
-      ;;
-    --help)
-      help
-      exit 0
-      ;;
-    *)
-      echo "Unknown option ${1}"
-      echo ""
-      help
-      exit 1
-      ;;
-  esac
-done
+begins_with_short_option()
+{
+	local first_option all_short_options='vmph'
+	first_option="${1:0:1}"
+	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+}
 
-echo "verbose flags: ${VERBOSE_FLAGS}"
-echo "months: ${MONTHS}"
-echo "period: ${PERIOD}"
+# THE DEFAULTS INITIALIZATION - OPTIONALS
+_arg_verbose="off"
+_arg_months="5"
+_arg_period="monthly"
+
+
+print_help()
+{
+	printf 'Usage: %s [-v|--(no-)verbose] [-m|--months <arg>] [-p|--period <arg>] [-h|--help]\n' "$0"
+	printf '\t%s\n' "-v, --verbose, --no-verbose: Include empty accounts in output. (off by default)"
+	printf '\t%s\n' "-m, --months: How many months should be shown. (default: '5')"
+	printf '\t%s\n' "-p, --period: The period by which the budget is grouped. Try 'monthly', 'quarterly' or 'yearly'. (default: 'monthly')"
+	printf '\t%s\n' "-h, --help: Prints help"
+}
+
+
+parse_commandline()
+{
+	while test $# -gt 0
+	do
+		_key="$1"
+		case "$_key" in
+			-v|--no-verbose|--verbose)
+				_arg_verbose="on"
+				test "${1:0:5}" = "--no-" && _arg_verbose="off"
+				;;
+			-v*)
+				_arg_verbose="on"
+				_next="${_key##-v}"
+				if test -n "$_next" -a "$_next" != "$_key"
+				then
+					{ begins_with_short_option "$_next" && shift && set -- "-v" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+				fi
+				;;
+			-m|--months)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_months="$2"
+				shift
+				;;
+			--months=*)
+				_arg_months="${_key##--months=}"
+				;;
+			-m*)
+				_arg_months="${_key##-m}"
+				;;
+			-p|--period)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_period="$2"
+				shift
+				;;
+			--period=*)
+				_arg_period="${_key##--period=}"
+				;;
+			-p*)
+				_arg_period="${_key##-p}"
+				;;
+			-h|--help)
+				print_help
+				exit 0
+				;;
+			-h*)
+				print_help
+				exit 0
+				;;
+			*)
+				_PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
+				;;
+		esac
+		shift
+	done
+}
+
+parse_commandline "$@"
+
+# OTHER STUFF GENERATED BY Argbash
+
+### END OF CODE GENERATED BY Argbash (sortof) ### ])
+# [ <-- needed because of Argbash
+
+set -e
 
 BUDGET_ACCOUNTS=(
-      'acct:expenses:Drugs'
-      'acct:expenses:Food'
-      'acct:expenses:Gift'
-      'acct:expenses:Groceries'
-      'acct:expenses:Hobby'
-      'acct:expenses:Living Space'
-      'acct:expenses:Tips'
-  # Projects are budgeted separately.
-  'not:tag:project'
+	'acct:expenses:Drugs'
+	'acct:expenses:Food'
+	'acct:expenses:Gift'
+	'acct:expenses:Groceries'
+	'acct:expenses:Hobby'
+	'acct:expenses:Living Space'
+	'acct:expenses:Tips'
+	# Projects are budgeted separately.
+	'not:tag:project'
 )
 
-START_MONTH=$(date --date "-${MONTHS}month" +%m)
-START_YEAR=$(date --date "-${MONTHS}month" +%Y)
+VERBOSE_FLAGS=""
+if [[ "${_arg_verbose}" = "on" ]]; then
+	VERBOSE_FLAGS="--empty"
+fi
+
+PERIOD="${_arg_period}"
+
+START_MONTH=$(date --date "-${_arg_months}month" +%m)
+START_YEAR=$(date --date "-${_arg_months}month" +%Y)
 
 START_DATE="${START_YEAR}-${START_MONTH}"
 
@@ -67,8 +138,11 @@ hledger balance \
   "--${PERIOD}" \
   --begin="${START_DATE}" \
   --budget \
-  --average "${VERBOSE_FLAGS}" \
+  --average \
+  "${VERBOSE_FLAGS}" \
   --tree \
   --sort-amount \
   --color=always \
   "${BUDGET_ACCOUNTS[@]}"
+
+# ] <-- needed because of Argbash
