[home/ledger] Add --months to hlcompare; declare used env var

diff --git a/home/yeldir/optional/desktop/office/hledger-scripts/hlcompare b/home/yeldir/optional/desktop/office/hledger-scripts/hlcompare
--- a/home/yeldir/optional/desktop/office/hledger-scripts/hlcompare
+++ b/home/yeldir/optional/desktop/office/hledger-scripts/hlcompare
@@ -2,12 +2,16 @@
 
 # Created by argbash-init v2.10.0
 # ARG_OPTIONAL_SINGLE([day-of-month],[d],[Day of the month on which to compare the previous months])
+# ARG_OPTIONAL_SINGLE([months],[m],[Amount of months to display],[6])
 # ARG_HELP([Compare account balances across the last six months])
+# ARG_USE_ENV([HL_MAIN_ACCOUNTS],[],[Array of accounts to take into account])
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
 ### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
 # Argbash is a bash code generator used to get arguments parsing right.
 # Argbash is FREE SOFTWARE, see https://argbash.io for more info
+
+# Setting environmental variables
 
 
 die()
@@ -21,21 +25,26 @@ die()
 
 begins_with_short_option()
 {
-	local first_option all_short_options='dh'
+	local first_option all_short_options='dmh'
 	first_option="${1:0:1}"
 	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
 
 # THE DEFAULTS INITIALIZATION - OPTIONALS
 _arg_day_of_month=
+_arg_months="6"
 
 
 print_help()
 {
 	printf '%s\n' "Compare account balances across the last six months"
-	printf 'Usage: %s [-d|--day-of-month <arg>] [-h|--help]\n' "$0"
+	printf 'Usage: %s [-d|--day-of-month <arg>] [-m|--months <arg>] [-h|--help]\n' "$0"
 	printf '\t%s\n' "-d, --day-of-month: Day of the month on which to compare the previous months (no default)"
+	printf '\t%s\n' "-m, --months: Amount of months to display (default: '6')"
 	printf '\t%s\n' "-h, --help: Prints help"
+	printf '\nEnvironment variables that are supported:\n'
+	printf '\t%s\n' "HL_MAIN_ACCOUNTS: Array of accounts to take into account."
+
 }
 
 
@@ -55,6 +64,17 @@ parse_commandline()
 				;;
 			-d*)
 				_arg_day_of_month="${_key##-d}"
+				;;
+			-m|--months)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_months="$2"
+				shift
+				;;
+			--months=*)
+				_arg_months="${_key##--months=}"
+				;;
+			-m*)
+				_arg_months="${_key##-m}"
 				;;
 			-h|--help)
 				print_help
@@ -78,21 +98,27 @@ parse_commandline "$@"
 
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
+set -e
 
-DAY_OF_MONTH=$(date --date '+1 days' '+%d')
-
-if [[ $_arg_day_of_month != '' ]]; then
-	DAY_OF_MONTH=$_arg_day_of_month
+if [[ $_arg_months -le 1 ]]; then
+	echo "months must be at least 2 to compare"
+	exit 1
 fi
 
-echo "day of month: ${DAY_OF_MONTH}"
+day_of_month=$(date --date '+1 days' '+%d')
 
-BEGIN_DATE=$(date --date '-6 months' '+%Y-%m')
+if [[ $_arg_day_of_month != '' ]]; then
+	day_of_month=$_arg_day_of_month
+fi
+
+echo "day of month: ${day_of_month}"
+
+begin_date=$(date --date "-${_arg_months} months" '+%Y-%m')
 
 hledger balancesheet \
 	--market \
-	--period "every ${DAY_OF_MONTH}th day" \
-	--begin "${BEGIN_DATE}" \
+	--period "every ${day_of_month}th day" \
+	--begin "${begin_date}" \
 	--end tomorrow \
 	--depth 4 \
 	--tree \
