[home/hledger] Rewrite hlcompare using argbash

diff --git a/home/yeldir/optional/desktop/office/hledger-scripts/hlcompare b/home/yeldir/optional/desktop/office/hledger-scripts/hlcompare
--- a/home/yeldir/optional/desktop/office/hledger-scripts/hlcompare
+++ b/home/yeldir/optional/desktop/office/hledger-scripts/hlcompare
@@ -1,32 +1,89 @@
 #!/usr/bin/env bash
 
-help() {
-  echo "Usage: hlcompare [-d|--day-of-month number]"
-  echo ""
-  echo "  -d|--day-of-month  Day of the month on which to compare the previous months"
-  echo "     --help          Show this help"
+# Created by argbash-init v2.10.0
+# ARG_OPTIONAL_SINGLE([day-of-month],[d],[Day of the month on which to compare the previous months])
+# ARG_HELP([Compare account balances across the last six months])
+# ARGBASH_GO()
+# needed because of Argbash --> m4_ignore([
+### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
+# Argbash is a bash code generator used to get arguments parsing right.
+# Argbash is FREE SOFTWARE, see https://argbash.io for more info
+
+
+die()
+{
+	local _ret="${2:-1}"
+	test "${_PRINT_HELP:-no}" = yes && print_help >&2
+	echo "$1" >&2
+	exit "${_ret}"
 }
+
+
+begins_with_short_option()
+{
+	local first_option all_short_options='dh'
+	first_option="${1:0:1}"
+	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+}
+
+# THE DEFAULTS INITIALIZATION - OPTIONALS
+_arg_day_of_month=
+
+
+print_help()
+{
+	printf '%s\n' "Compare account balances across the last six months"
+	printf 'Usage: %s [-d|--day-of-month <arg>] [-h|--help]\n' "$0"
+	printf '\t%s\n' "-d, --day-of-month: Day of the month on which to compare the previous months (no default)"
+	printf '\t%s\n' "-h, --help: Prints help"
+}
+
+
+parse_commandline()
+{
+	while test $# -gt 0
+	do
+		_key="$1"
+		case "$_key" in
+			-d|--day-of-month)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_day_of_month="$2"
+				shift
+				;;
+			--day-of-month=*)
+				_arg_day_of_month="${_key##--day-of-month=}"
+				;;
+			-d*)
+				_arg_day_of_month="${_key##-d}"
+				;;
+			-h|--help)
+				print_help
+				exit 0
+				;;
+			-h*)
+				print_help
+				exit 0
+				;;
+			*)
+				_PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
+				;;
+		esac
+		shift
+	done
+}
+
+parse_commandline "$@"
+
+# OTHER STUFF GENERATED BY Argbash
+
+### END OF CODE GENERATED BY Argbash (sortof) ### ])
+# [ <-- needed because of Argbash
 
 DAY_OF_MONTH=$(date --date '+1 days' '+%d')
 
-while [ $# -gt 0 ]; do
-  case $1 in
-    -d|--day-of-month)
-      DAY_OF_MONTH="${2}"
-      shift; shift;
-      ;;
-    --help)
-      help
-      exit 0
-      ;;
-    *)
-      echo "Unknown option ${1}"
-      echo ""
-      help
-      exit 1
-      ;;
-  esac
-done
+if [[ $_arg_day_of_month != '' ]]; then
+	DAY_OF_MONTH=$_arg_day_of_month
+fi
 
 echo "day of month: ${DAY_OF_MONTH}"
 
@@ -40,3 +97,5 @@ hledger balancesheet \
 	--depth 4 \
 	--tree \
 	"${HL_MAIN_ACCOUNTS[@]}"
+
+# ] <-- needed because of Argbash
