[home/office/ledger] Rewrite hlevents to use argbash; Restructure arguments
Now show the cashflow-by-event view by default and has a single flag to
instead show the incomestatement-by-account view.

diff --git a/home/yeldir/optional/desktop/office/hledger-scripts/hlevents b/home/yeldir/optional/desktop/office/hledger-scripts/hlevents
--- a/home/yeldir/optional/desktop/office/hledger-scripts/hlevents
+++ b/home/yeldir/optional/desktop/office/hledger-scripts/hlevents
@@ -1,62 +1,141 @@
 #!/usr/bin/env bash
 
-help() {
-  echo "Usage: hlevents"
-  echo ""
-  echo "  -p|--pivot  Groups transactions by event instead of account"
-  echo "  -b|--begin  Override begin date. Default is 6 months ago"
-  echo "  -e|--end    Override end date. Default is in 6 months"
-  echo "     --cf     Use cashflow report instead of incomestatement. Shows total per event. Use together with -p"
-  echo "     --help   Show this help"
+# ARG_OPTIONAL_SINGLE([begin],[b],[Begin date. Default is six months ago])
+# ARG_OPTIONAL_SINGLE([end],[e],[End date. Default is in six months])
+# ARG_OPTIONAL_BOOLEAN([by-account],[a],[Group transactions by account instead of event],[off])
+# ARG_HELP([Show data related to events])
+# ARGBASH_GO()
+# needed because of Argbash --> m4_ignore([
+### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
+# Argbash is a bash code generator used to get arguments parsing right.
+# Argbash is FREE SOFTWARE, see https://argbash.io for more info
+
+
+die()
+{
+	local _ret="${2:-1}"
+	test "${_PRINT_HELP:-no}" = yes && print_help >&2
+	echo "$1" >&2
+	exit "${_ret}"
 }
 
-PIVOT_FLAG='acct'
-BEGIN_DATE=$(date --date '-6 months' '+%Y-%m')
-END_DATE=$(date --date '+6 months' '+%Y-%m')
-REPORT='incomestatement'
 
-while [[ $# -gt 0 ]]; do
-  case $1 in
-    -p|--pivot)
-      PIVOT_FLAG='event'
-      shift;
-      ;;
-    -b|--begin)
-      BEGIN_DATE="${2}"
-      shift;
-      shift;
-      ;;
-    -e|--end)
-      END_DATE="${2}"
-      shift;
-      shift;
-      ;;
-    --cf)
-      REPORT='cashflow'
-      shift;
-      ;;
-    --help)
-      help
-      exit 0
-      ;;
-    *)
-      echo "Unknown option ${1}"
-      echo ""
-      help
-      exit 1
-      ;;
-  esac
-done
+begins_with_short_option()
+{
+	local first_option all_short_options='beah'
+	first_option="${1:0:1}"
+	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+}
 
-echo "pivoting: ${PIVOT_FLAG}"
-echo ""
+# THE DEFAULTS INITIALIZATION - OPTIONALS
+_arg_begin=
+_arg_end=
+_arg_by_account="off"
 
-hledger "${REPORT}" \
-    --monthly \
-    --market \
-    --begin "${BEGIN_DATE}" \
-    --end "${END_DATE}" \
-    --forecast \
-    --pivot "${PIVOT_FLAG}" \
-    --row-total \
-    "tag:event"
+
+print_help()
+{
+	printf '%s\n' "Show data related to events"
+	printf 'Usage: %s [-b|--begin <arg>] [-e|--end <arg>] [-a|--(no-)by-account] [-h|--help]\n' "$0"
+	printf '\t%s\n' "-b, --begin: Begin date. Default is six months ago (no default)"
+	printf '\t%s\n' "-e, --end: End date. Default is in six months (no default)"
+	printf '\t%s\n' "-a, --by-account, --no-by-account: Group transactions by account instead of event (off by default)"
+	printf '\t%s\n' "-h, --help: Prints help"
+}
+
+
+parse_commandline()
+{
+	while test $# -gt 0
+	do
+		_key="$1"
+		case "$_key" in
+			-b|--begin)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_begin="$2"
+				shift
+				;;
+			--begin=*)
+				_arg_begin="${_key##--begin=}"
+				;;
+			-b*)
+				_arg_begin="${_key##-b}"
+				;;
+			-e|--end)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_end="$2"
+				shift
+				;;
+			--end=*)
+				_arg_end="${_key##--end=}"
+				;;
+			-e*)
+				_arg_end="${_key##-e}"
+				;;
+			-a|--no-by-account|--by-account)
+				_arg_by_account="on"
+				test "${1:0:5}" = "--no-" && _arg_by_account="off"
+				;;
+			-a*)
+				_arg_by_account="on"
+				_next="${_key##-a}"
+				if test -n "$_next" -a "$_next" != "$_key"
+				then
+					{ begins_with_short_option "$_next" && shift && set -- "-a" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+				fi
+				;;
+			-h|--help)
+				print_help
+				exit 0
+				;;
+			-h*)
+				print_help
+				exit 0
+				;;
+			*)
+				_PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
+				;;
+		esac
+		shift
+	done
+}
+
+parse_commandline "$@"
+
+# OTHER STUFF GENERATED BY Argbash
+
+### END OF CODE GENERATED BY Argbash (sortof) ### ])
+# [ <-- needed because of Argbash
+
+begin_date="${_arg_begin}"
+if [[ -z $_arg_begin ]]; then
+	begin_date=$(date --date '-6 months' '+%Y-%m')
+fi
+end_date="${_arg_end}"
+if [[ -z $_arg_end ]]; then
+	end_date=$(date --date '+6 months' '+%Y-%m')
+fi
+
+if [[ $_arg_by_account = "off" ]]; then
+	hledger cashflow \
+		--monthly \
+		--market \
+		--begin "${begin_date}" \
+		--end "${end_date}" \
+		--forecast \
+		--pivot "event" \
+		--row-total \
+		"tag:event"
+else
+	hledger incomestatement \
+		--monthly \
+		--market \
+		--begin "${begin_date}" \
+		--end "${end_date}" \
+		--forecast \
+		--pivot "acct" \
+		--row-total \
+		"tag:event"
+fi
+
+# ] <-- needed because of Argbash
